#!/bin/bash
# Script to permanently disable systemd-resolved on Ubuntu
# Run with: sudo bash disable-resolved.sh

set -e

echo "========================================="
echo "Disabling systemd-resolved for dnsmasq"
echo "========================================="

# Backup current resolv.conf
echo "[1/6] Backing up current resolv.conf..."
sudo cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)

# Stop systemd-resolved
echo "[2/6] Stopping systemd-resolved service..."
sudo systemctl stop systemd-resolved

# Disable from starting at boot
echo "[3/6] Disabling systemd-resolved at boot..."
sudo systemctl disable systemd-resolved

# Remove the symlink
echo "[4/6] Removing resolv.conf symlink..."
sudo rm -f /etc/resolv.conf

# Create new resolv.conf pointing to local dnsmasq
echo "[5/6] Creating new resolv.conf..."
cat << EOF | sudo tee /etc/resolv.conf
# Generated by disable-resolved.sh for dnsmasq
# Primary DNS - local dnsmasq container
nameserver 127.0.0.1
# Fallback DNS servers
nameserver 1.1.1.1
nameserver 8.8.8.8
# Search domain
search corp.internal
options timeout:2 attempts:3
EOF

# Prevent NetworkManager from overwriting
echo "[6/6] Preventing NetworkManager from modifying resolv.conf..."
if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
    sudo sed -i '/^\[main\]$/a dns=none' /etc/NetworkManager/NetworkManager.conf
    sudo systemctl restart NetworkManager
fi

# Make resolv.conf immutable
echo "Making resolv.conf immutable..."
sudo chattr +i /etc/resolv.conf 2>/dev/null || echo "chattr not available, using chmod..."
sudo chmod 444 /etc/resolv.conf

# Verify
echo ""
echo "Verification:"
echo "-------------"
echo "1. Port 53 status:"
sudo netstat -tulpn | grep :53 || echo "Port 53 appears free"
echo ""
echo "2. Current DNS servers:"
cat /etc/resolv.conf
echo ""
echo "3. systemd-resolved status:"
sudo systemctl status systemd-resolved | grep -E "Active|Loaded" || true
echo ""
echo "Done! You can now run: docker-compose up -d"